version: '3.8'
services:
  frontend:
    container_name: frontend
    build: frontend/
    ports:
      - "8501:8501"
    networks:
      - network
  backend:
    container_name: backend
    build: backend/
    ports:
      - "8502:8502"
    networks:
      - network
networks:
  network: